#!/bin/bash

# Copyleft Fabien Wernli
# 20220609
# record desktop after choosing rectangle

# requirements:
# https://github.com/Enselic/recordmydesktop
# https://github.com/naelstrof/slop

# acknowledgemens:
# thanks to frobnitz#suckless for the pointer to slop

DEBUG=${DEBUG:-}
debug()
{
  if [[ -n "$DEBUG" ]]; then
  	echo $@
  fi
}

if geometry_raw_output=$(slop -of "%x %y %w %h %i"); then
	debug $geometry_raw_output
	read -r x_offset y_offset width height window_id <<< $geometry_raw_output
	debug width=$width height=$height x_offset=$x_offset y_offset=$y_offset
  recordmydesktop -x $x_offset -y $y_offset --width=$width --height=$height --no-sound --on-the-fly-encoding
else
	echo "Something went wrong while detecting window geometry. Try to restart script with DEBUG=1 env variable." 1>&2
fi

